version: '3.1'

services:
  db:
    build: .
    container_name: api-db
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projectdb
